version: '3'
services:
  geth:
    image: ethereum/client-go:latest
    volumes:
      - ./data:/root
    command: 
      - "--syncmode"
      - "full"
      - "--cache=1024"
      - "--http"
      - "--ws"
      - "--metrics"
      - "--maxpeers"
      - "30"
    ports:
      - "127.0.0.1:8545:8545"
      - "127.0.0.1:8546:8546"
      - "127.0.0.1:30303:30303"
    restart: on-failure