version: '3'
services:
  geth:
    image: ethereum/client-go:latest
    volumes:
      - ./data:/root
    command: 
      - "--syncmode"
      - "full"
      - "--cache=1024"
      - "--http"
      - "--ws"
      - "--metrics"
      - "--maxpeers"
      - "30"
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    restart: on-failure